#ifndef QTDEIKSTRAALGORYTHM_GLOBAL_H
#define QTDEIKSTRAALGORYTHM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTDEIKSTRAALGORYTHM_LIBRARY)
#  define QTDEIKSTRAALGORYTHMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTDEIKSTRAALGORYTHMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTDEIKSTRAALGORYTHM_GLOBAL_H
